== THE ACKSCENE FAMILY

== OVERVIEW:

The Ackscenes are a rather new family emerging from aftermath of the Ape Revolt
gaining a foot hold into the scene of familys mostly due to there fathers intellect
and social intelligence, as well as there niece market in trading arms.

Of course with every rise come it's turbulence's as the 

=== NOVENTON

An old family butler who's worked under the Ackscenes for years ensuring the
smooth functioning of there manors staff as well as personal consul for those
he's close too, he's proven to be both a great asset and good friend to Meldoa's
father, whom he (before Meldoa came to preface) relied upon to rely the status 
of his childrens endeavor's and welfare directly to him.

However before he met his friend and boss Junias Ackscene, he had worked at a 
variety of manors before, all of which had either a handful or a small group of 
apes, this has lead him to have a more softer edge then most when it comes to 
interacting with said people, however he still posses some prejudices
