== THE ACKSCENE FAMILY

== OVERVIEW:

The Ackscenes are a rather new family emerging from aftermath of the Ape Revolt
gaining a foot hold into the scene of familys mostly due to there fathers intellect
and social intelligence, as well as there niece market in trading arms.

Of course with every rise come it's turbulence's as there rise to power meant
the displacement of another, but despite those troubles, the high family's
seem to agree with his rise and Ackscene family looks poised to secure it self
in the family's major.

=== JUNIAS

Junias, the head of the family, the falcon of Gloshter, the man has gotten 
quite the reputation for himself, considering his recent feat of his rise,
and nobody disagrees, investing in the arms industry before the war was a good
play, even better when you knew how everything in those few short years would 
play out.

Some people wonder however if he has any human insiders in the colony's
that revolted, due to the accuracy of some of his preparations

=== NOVENTON

An old family butler who's worked under the Ackscenes for years ensuring the
smooth functioning of there manors staff as well as personal consul for those
he's close too, he's proven to be both a great asset and good friend to Meldoa's
father, whom he (before Meldoa came to preface) relied upon to rely the status 
of his childrens endeavor's and welfare directly to him.

However before he met his friend and boss Junias Ackscene, he had worked at a 
variety of manors before, all of which had either a handful or a small group of 
apes, this has lead him to have a more softer edge then most when it comes to 
interacting with said people, however he still posses some prejudices

=== MELDOA

One of Junias daughters as well as the one he prizes the most she is considerably
intelligent, and uses a wide array of means to accomplish her goals even if
some of those methods are somewhat controversial, she tends to work well under
pressure being able to keep a cool head unlike her father, whom needs to be 
calm before he can think clearly.

And recently he's been getting on her nerves, as if she going to become 
the next head of the family she'll need to start one of her own as insurance
in the event of an untimely death, and because her father methods are somewhat
forceful she is looking for a way out.

=== ERIC
