== A CHOICE THAT DOESN'T EXIST
:autofit-option:

=== MELDOA

Meldoa got into the car reading through the endless paperwork of profit margins
and facility productivity sheets, shes tends to make a habit of going around checking up
on each location to verify there reports, some of her sisters and brothers hate her
for this but she adamant about the accuracy of her books, as well as protecting
her fathers investments.
    
Her first stop was one of her brothers districts he was the one responsible
for arms shipments both in and out of the city and by nature of 
the business, everything required a certain amount of extra care when it came 
to ensuring everything was running smoothly. In fact one of the reasons father 
put this bother in charge of this operation was because he was reasonable, 
trustworthy and in good relations with Meldoa.

"Ah, nice seeing you again sister." Denna (Meldoa's bother) said as she stepped
into his office, the rough oak floor and dusty interior making her nose tickle.
"May I see your internal paperwork." She asked, never the one for pleasantry's
instead favoring bluntness one of the many reasons where she is today, however
every blunt object has there edge.

"Yes, yes I already have them right here," Denna then plopped a mound of paper 
onto his desk. "I assume you also want a tour," He said wrapping up the 
paperwork with a thick piece of linen thread, Meldoa nodded her head. 

The tour did not last long as it was only the warehouse, meeting locations
would always be switched, and it would be odd for a family accountant to be
at a place where supposedly nothing was supposed to be delivered, and the state
mostly handled there own shipments so there was no need for that either.

"Anything else you'd like to see." He asked as they reached the entrance,
there where only minor discrepancies many of which could be chocked up to
errors, or changes in season. She shook her head, "no that will be all see you
next quarter," she then left and returned to her car. "Hena's next," Meldoa said,
her driver nodded, starting the car and putting it in gear.

Meldoa had 25 siblings many of which where still young and didn't command
enough respect to be able to hold there own district, or business, only 11 had
reached such a point, and she couldn't possibly do these 11 in a single day
so she did it by priority, Denna was always the first due to the sensitive nature
of the business, whilst everyone else usually got on top because of large discrepancies
or recent events that compelled an early visit.

It wasn't long until she found herself at one of Hena's warehouses, a warehouse
that was the location of a rather grueling crane accident that left a few people
dead and one injured, at least that was what she remembered when the report got
to her desk, in all honestly she didn't care much for the people they where all
apes anyways, what she did care about was the cargo listed on the manifest.

Expensive jewelry some of which where damaged beyond repair, one and a half 
tons of flour that was lost to the harbor, as well as a bunch of other 
miscellaneous products which where damaged. 

She stepped into her sisters office, her child jumping off
of a seat that was in the corner of the room. "Auntie!" She yelled, whilst Meldoa
was by all means cold, she wasn't one to neglect a child in fact she has spent many 
hours caring for her sisters and brothers children effectively acting like a nanny
however she did not posses any of her own.

She wasn't unable to do so, her instrument was still apart of her
and functioned as expected but unfortunately for her father lacked any such will
to put that instrument to use, her sisters have speculated she's too self centered
to think of such things, or to care but they had failed to consider that she 
just wasn't interested at the moment.

She picked up the child and brought her niece into her arms. "How are you doing
Francis?" Meldoa asked, Meldoa had always been a hypocrite when it came to youth
in the terms of small talk perhaps she knew more to motherhood then interacting
properly with her other wolfkin. "I'm doing great, I lernt bigger words." Meldoa
smiled, which if one had saw would probably see them drop dead from shock, 
"Learned, dear."

"Learned." The little pea respond her ears perking up to the ceiling, an
easily excited little learner, "yes, dear, L-E-A-R-N with an E-D at the end."

"Ooohh."

"Now, dear where might I find your mother."

"Oh, she said she would be in the, ugghh, you know place with all the big boxs."

"The floor?" Meldoa asked.

"Yeah, yeah." Francis immediately responded. Meldoa held the child more firmly 
"Well lets go get here then." The child started giggling excited to be able to 
wander about with her aunt they walked for some time, until they came across a
section which housed Hena, they both immediately locked eyes, the sister 
immediately possessing an expression of annoyance.

"Let me guess, quarterly checkup," Meldoa nodded, and then her sister exhaled.
"Come, I'll do the tour and then get you your documents, and I'll also assume you
want to talk about the crane accident." Hena then turned around and Meldoa followed.

"Have you handled the reimbursements," Meldoa asked. "Yes, yes we've also tooken
care of procedure to ensure that it never happens again." Meldoa nodded albeit a
little skeptically, her sister is well known to her to care about time more then
about quality and these accidents have happened in the past because of this
mentality. "May I ask what changes." Her sister looked back at her, Hena knew
she couldn't blame her for the suspicion.

"We've changed the ropes for chains, we also do inspections every week, to make
sure that there properly fit for use." Hearing direct names to solutions put 
Meldoa at ease hopefully she finally reaching the point where she's recognizing 
speed is not always fast.

Hena then lead Meldoa through the warehouse things, could obviously be better
but the most glaring issue was the sagging wood beam in the back corning, in fact
such issue was starting to become noticeable on the outside of the warehouse as
the weight of the create was starting to push out the brick wall but only slightly
for now.

"And here's your paperwork." Hena said placing the stack onto the table not 
even bothering to tie it. "Auntie, auntie, can I go over to your place." The little
pea excitedly said, "that's all up to your mother dear," She then looked at Hena
with pleading eyes, "fine do as you wish." Meldona, then grabbed the stack of paper
placing it tightly underneath her arm, as she carried the little pea out of the 
out of the brick building, and into the car. 

"Hello, miss Francis," the driver said with a smile, brightening up his day. 
"Hey," she responded as she found her seat, energetically bouncing her feet
off of the end. It wasn't hard for Meldoa to find time for the children,
all here responsibility's could be mostly dealt with in one place that being
her manor, in fact she rarely left such a place due to that fact, which invoked 
a constant prodding voice into her mind, that being one that belong to her father.

Meldona has been a virgin from birth, and has never married, instead paying more
attention to her study's, which lead her to becoming the familys accountant,
and now due to her role and her fathers increasing preface and reliance on her
to ensure the smooth running of there businesses, would like to see her bring
children into the family. In recent years his pestering had gone from somewhat
tolerable to down right harassment, right to the point of luring her into blind
dates and even recommending the injection of semen into her womb, all methods, 
and potential partners she firmly rejected.

Although she knew he was coming out of a place of business and fatherly duty
she was starting to run out of patience, and her annoyance was on a fast track
to hostility, She pondered of what to do, she understood that she could just
ignore him, as he had never disrespected his children's agency but she also
just wanted him to stop and be quiet on the ordeal.

She thought a little longer until she decided that it would be a good idea to
shelve it until she was alone and didn't have a child in tow. "I think we'll call
it a day for now bring me to fathers house." Meldoa said beginning a comb through
the documents before her. "I thought we where going to your house," Meldoa smiled.
"We will dear, I just need to talk to your grandfather first." Her eyes opened
up, "oh, grandpa's house I thought we where going to someone else's." Francis 
always had trouble with remembering the significant of certain words, her mind, 
and sometimes it felt like she only took part of a sentence in at a time.

"My father is your grandfather," Meldoa immediately tried to teach,
"your father is my grandfather... How does that work." Meldoa smiled
at the excited little pea, "when I was born, I was born under your grandfather,
which makes him my father, as I was born under him, and since your mother, which is my
sister, was also born under him, when you where born made my father your grandfather."
Meldoa went as slow she could letting the child digest what was being spoken.
"Oh." the pea said. "imagine it like a tree that's grown upside down, each branch
is a separate person adding to the whole tree." The child's eyes practically popped out
of her head. "Oh, so that means lisa is your sister too."

"Yes, dear."

"And Semosa is your brother, and Tela is your mother." She caught on quick,
Meldoa thought to herself, happy over the fact that she was able to grasp something
new about the world so quickly. "Yes, dear." Meldoa repeated. "Oh, that's why you
guys all act weird around each other," Meldoa couldn't help but laugh a little,
but what the child said isn't wrong from her perspective as to her they do act 
different when around each other especially with Meldoa as she is the favored
child. "I wish mommy would teach me more," the child spoke, Meldoa sorta nodded
trying to remain natural in her expression.

The little pea was by no means neglected but, children require special attention
always, and if that attention is not met it tends to harbor similar feelings of
neglect. Meldoa knew it was for the most part her sisters fault for not being
more attentive to the child's feelings and time. Her sister always had this
knack for getting things done as quickly as possible in every aspect of her life.

It wasn't long before they found themselves at fathers manor, the white granite
building towing over all the little shops and residences that laid beyond it's 
steel gates. Some would say it was an odd place for a manor, but this residence
had been built long ago when this was once field.

They pulled up to the front gate, one of the family's men coming to it, immediately
recognizing the vehicle as he did, he opened the gate waving them through and the 
driver did as instructed, pulling up to the front of the building it's ornately
carved door not even gaining a grain of attention from Meldoa who's become all to
familiar with the sight, while Francis became infatuated with it's precise carvings 
upon crossing it each time.

They both entered into the man hall the child running about checking everything
there was to see from the paintings to the walls, down to the tiny little ornaments
on the railings, Meldoa continued up the stairs whilst the child stared with
glistening eyes at all these things, smiling as she did, and once she reached the 
top she gently called out Francis's name and she came running.

Meldoa understood the child wanted to see more, as she once did when she was with 
the litter, but she couldn't let her out of her sight, even in the safety of one
of her family's buildings. 

Francis hardly gets to see her uncle and only has saw him during
family's gatherings and the occasional visit, he was nothing short of an enigma
to her, he was quiet and had a look to him that told you he was a man who barely
kept a quiet mind, with this the child coined her uncle the nickname strange old
man, she was wise enough to never speak this with anyone but herself.

The two then made it too his study, a place he spent much time in, a place where
he's made plenty of decisions. They stepped through the double doors and where
greeted my incense, Meldoa's father was sometimes anxious when it came to certain
matters, he used incense and tea to help stave out rampant anxiety something that 
he has noted effects his thinking, something was obviously bothering his mind.

Meldoa and Francis then became seated, father only acknowledging there presence
for a moment before writing down in that moment what he was thinking. 
"Welcome, Meldoa and I see you brought a little one." Meldoa nodded, "and I 
assume your here updateing me on alls the goings on." She nodded once more. 
"I've only attended to the major concerns of this quarter, yours truly and my 
sister Hena,"

"Ah yes, Hena and I assume everything is alright with Denna."

"Yes, Denna business looks to be running well, I have yet to look over the documents
but I see nothing different in my years overseeing him."

Father nodding his head pleased by the consistency and predictability that these
two operate on, there good children and he wishes them well.

"However, Hena's has made an effort in improving the main warehouse on the port
river."

The father widened his eyes a little, "you mean I didn't have to do anything."

"Not in this instance no, that being said there is a sagging beam, and a pallet 
of cargo is currently pushing out the wall on the third floor, she made no comment
and actively looked away when I brought my eyes to it."

Father exhaled, "just when I was getting hope... That's not something I can overlook,
losing a warehouse especially now, will not be ideal, I'll hire a crew from
Deshane, have them clean up another up and coming mess." Father then swore under 
his breath, making sure the child could not hear.

"Anything else." Meldoa shook her head, "those where the only two I could get to
for today I intend to visit the rest in the following days." Father seemed to shift
in his chair uneasily. "Make sure there quick, things are getting uncomfortable,
with the Terina family." Meldoa cocked her eyebrow. "Another war," father leaned
forward a bit, thinking, "maybe," "I suppose then I should take my leave." Meldoa
then proceeded to rise. "Come, Francis it's time to go to my residence." The child,
jumped off the couch, and rain to the door waiting for Meldoa to open it.

"Meldoa, before you go any developments on a husband, I know a few men who are 
intrested," at this moment Meldoa decided she had, had it with her fathers 
continued assault on her marriage status, but she wasn't going to take it out 
on him here, no, no, she's much too clever and much too willing for such an 
uncouth display. "I'm working on it father." Meldoa said as she hurried out the 
door with the little one in tow, in fact she already went over this plan long ago.

Her and the little one both got into the car, as Meldoa went over the details of 
her plan in her head once more, to marry a fellow wolfkin would send the wrong 
message it would mean I'd be serious about becoming a wife and bearing children,
and it would just ramp up my fathers assault however an ape makes the perfect 
threat, perfectly taboo to the point where people are disgusted by it, she 
thought to herself, while a mischievous grin began to take form,
the perfect threat. All that she has to do is go about this carefully.

They soon arrived at Meldoa's manor, a large gated house just outside the city 
limits, it's land was small in comparison to some of the manors she had been to
but nonetheless to any common folk it was still vast, the child rushed inside with
Meldoa right behind, both having separate reasons as to why there rushing ahead.

Meldoa tended to the child all night, ensure her time wasn't wasted, she 
learned, played, and ate until she had become tired. Meldoa decided
it was best to wait until this moment, that way she wouldn't feel guilty doing
her work, it was all going to run into the night anyways.

=== SIRCE

Sirce Woke up in his bed after another work week gone by, his muscles ached
but they always did when he first woke. He slowly got up, enjoying the small 
respite he had this Sunday, when the wolfkin would grant at the very least a 
single day off.
    
He then noticed the sweat on the sheets below him, his neighbors often talked
to him about his screaming and wailing, it was three months now since it happened,
he imaged he would've gotten over it by now, but the memory of the cable snapping
from the crane and the resulting aftermath still shook him, at this point the only
thing he wanted was his shoulder to return to how it was.

He stepped into his pantry taking a slice of meat off of a dried carcass, a gift
he received from a local butcher after helping him pay off his debts to a gang, 
it's done him well these past few months. Sirce then took note of all the little
things inside, compiling a list in his head of the goods he will need to get on
his trip out, he didn't have alot of money but a few cents can bring 
you along way with what he was shopping for.

He quickly left his apartment hoping to make this journey quick as it was his
final day off and he was hoping to spend the rest of it in the park. He never
really was a fan of his apartment it was cramped, dusty, and obviously need some
love from the landlord, but he knew it wasn't going to get any better there 
besides, he'd rather look at the flowers.

He didn't necessarily like flowers in the way most people like them, as in the
beauty they bestow, he liked them more that they reminded him of home, his mother 
is a florist whom saw some pretty big wigged visitors and paid far more then what
she asked for, and his father was a carpenter hence Sirce's last name.

But even with all the financial backing from there affluent visitors they where
few and far between, the little customers, the locals always made the bulk of
there sales, and they where leaving there local town in droves as all the skilled
labor went to the city's, and despite Sirce's skills in both his mothers and fathers
trade, he's found himself in the gutter at a warehouse.

It wasn't hard to figure out why, why hire someone who has years of experience
when you can hire an idiot off the street, tell him how to use a machine,
and walk away as he produces an identical piece to that of an actual carpenter,
and all the floral shops are small, local, and don't pay well either, 
he was hoping to land a spot at Spectacle a world renowned flower garden and flower 
shop but that was in vain as wolfkin where only allowed to work there, in fact 
all the places with good pay only hired wolfkin.

In a way Sirce kinda wished he was stupid, because then at least he would feel 
like he was getting a good deal, but he knew that wouldn't be a good predicament
either, he exhaled as he went into the local market, scanning the selves for what
he needed.

Canned peas, onions, potatos, he wondered what he'd do if mom hadn't taught him
how to cook, he then went to make his purchase. "Hey, Sirce." Sirce at this
point was a regular, a rather helpful regular as he often was paid for odd jobs,
fixing doors, dressers, cabinets, point was the local apes knew who to go to when
something beyond there scope happened.

"Hey, Neeva." Neeva wasn't a very tall man, malnourishment from what he heard 
had it's way with him in his youth, even despite the fact he's been stealing 
food from people here since he was little, and due to his experience's he 
was the one who helped Sirce the most upon coming here, especially when it came 
to avoiding trouble. 

"Hey." Sirce replied, Neeva then looked at Sirce's shoulder, 
"is it still busted," Sirce nodded. "Wish we had a doctor." Sirce said, 
"Yeah, wish they let us into the collages, at least then we'd have 
less assholes." Sirce chuckled, "Say how was it back home?" Neeva asked, 
Sirce shrugged, "not too bad, the wolfkin where nice too." "Really?" Neeva ask, 
sounding surprised, Sirce nodded, "yes, of course I don't know how it is now, 
it's probably a ghost town," Neeva nodded, "ghost town sounds preferable to all 
of this." He sorta exhaled. 

"Sorry those fucking extortionists came today, I'm just feeling down again." 
Oh it's that time, Sirce thought, "it's alright we all need to let it out," 
Neeva smiled. "Maybe one day I can run in a field," Sirce shook his head, 
"land owner will shoot yeah," Neeva exhaled again, "fucking dammit you can't run 
away from it can yeah." Sirce nodded, "still better then here I guess," they both 
chuckled, "well, have a good one, Neeva." Neeva raised his hand, "and to you the 
same."

Sirce, then left and continued back to his apartment, feeling a little homesick,
but he had to stay here so that his mother and father wouldn't suffer his current 
fate, as in his mind the family couldn't suffer a worst fate then losing the 
greenhouse and workshop.

Once, Sirce put away his acquired goods, he then left for the park planning to enjoy 
the rest of his afternoon secretly collecting seeds, and sending them back to
his mother.

The next day he quickly made himself something to eat as he knew he was going
to be worked to the bone once again, and he could only imagine the extent 
his shoulder could bare, last time he went to work he had to get someone else
to help him pick up some crates, luckily they where sympathetic enough to help.

And as he suffered throughout the day his wolfkin manager came to him. "Boss,
want's to see you upstairs." The wolfkin spoke, Sirce then followed, am I being
fired, he thought feeling a little anxious as he climbed the stairs, he then
entered the room and notice a woman he hadn't recognized standing across from the
boss, she turned around and look at him with an apprising glare.

"So this is the one you want to be ride of," the wolfkin woman said.
His boss then leaned back in her chair, "yeah, he blew his shoulder out from the
crane accident he's been slow ever since," the strange woman walked a little closure,
"eh, he will do, Its'ven." He felt someone he hadn't notice grab his shoulder,
"come on, follow me ape," Sirce had begun to find the word more then distasteful
in his time here it was used for everything in reference to his race, 
simplified, derogatory, with no sense or thought placed behind the people it 
described, like he isn't even something that's worth thinking about.

However, there where no objecting these commands if he was a little more proud
and a little more stupid he could protest, but with how everyone acted in this
room to each other he knew that these where all members of a family, so all
he could just do was hope that whatever they where planning wasn't going to be
his end.

He soon found himself being escorted to a car, a stack of papers laying on the 
seat across from him, the wolfkin Its'ven he believed his name was called, 
getting in first finding the large man in the middle, 
the female wolfkin soon coming out of the warehouse finding her seat across from 
him, separated by Its'ven.

"Mr. Carpenter, my name is Meldoa Ackscene from here on out I will be your
fiance," Sirce began to sweat, he new he wasn't important and that there was
no reason for him to be held at such a level to be married into a
family, unless he was meant to be played as some pawn in a game he didn't
understand.

"And I will word this plainly, since you are an ape, I have no intention to actually
marry you or bear your children, only in the event I require to I will do so in 
both prospects, however you are merely just to act like my fiance." Sirce was at 
first understandably in shock, which eventually made it's way into an onset of 
depression, as he knew or at least felt like he knew, he was going to become a 
pet bird in a gilded cage with no will of his own, he only hoped however he'd
be as valued as a pet pigeon.

That fact might be exciting for some whom posses certain proclivities, but to
him it was a sentence worse then death, what was to become of his mother and father,
money, freedom, was this going to be indefinite? All these questions swirled in 
his mind, still he kept a poker face.

He gently brought his glare to the woman who called herself Meldoa, "is there pay."
"Sure, now that you say it I'll give you an allowance... Hmmm, yes ground rules,"
Sirce, knew this was going to be the moment that was going to decide whether it
was going to be a prison or a well looked after prison.

"You'll be given your own room where you may place your personal belongings,
however you cannot damage that room, also you may not leave the premises without,
my permission, or without me in company." A gilded cage just as he predicted,
"my butler will lay down the rest of the ground rules, as well as teach you proper 
manners."

He exhaled to himself, he could jump out of the car now, it'll hurt but,
He looked at the lock, it's pressed down they'd notice and catch on in an instant,
then they continue to suspect every move he'd make would come with intent to escape,
better to wait for a better opportunity.

"Understood." The woman said, he then looked back at the woman, "I guess." She 
then gave him a less then delightful expression. "Understood, mam," he then 
added, can't be passive aggressive with her. "Good."

After some time, they soon arrived at what he assumed was her manor, he quickly 
noted the large yard, hoping that they at least let him out there to enjoy himself
once and awhile.

They then entered her complex, there where a few guards, but nothing to write
home about, probably didn't need them all the way out here, Sirce thought,
however nothing about the place eased him, he was alone with no one to fight for
him but himself, and while many mistreatment's by wolfkin where mostly verbal,
there where plenty who preferred violence.

The butler then came down from the second story. "Is, this your, "*husband*," milady."
Meldoa nodded, the butler gave him an apprising look, but it was less assigning
value to a pet, and more determining the usefulness of a person, "hmm, quite young,
say I heard you worked in a warehouse." The butler said as he stood in front of him.
"Yes," he stroked his well groomed beard. "Good, I could use the help."

There was then a period of silence, Meldoa locking eyes with the butler, "milady,
we've finished up early for today in terms of menial tasks, may I show him his 
courtiers, and hand him his uniform and let him rest up." Meldoa nodded, "I do 
not see a reason not to."

"You may follow me then, oh and what might your name be." "Sirce." The butler
nodded. "It's a pleasure to make your acquaintance then, Sirce, mine is Noventon."
The butler then quickly changed his direction to one of the lower wings of the 
manor, Sirce in tow.

While, Sirce was still concerned by those that surrounded him in this place,
he was beginning to like the butler even though he obviously share some sentiments
with the other wolfkin, he was nether hostile, or demanding, it felt weird to Sirce,
at this point in time, to be treated with some semblance of respect by a wolfkin.

The butler then approached a door, and opened it revealing the small interior,
with a single bed pressed against the wall, "this will be your quarters from
now on," Sirce nodded as he continued inside, well at least it's cleaner then
my apartment, he thought.

"I'll let you familiarize yourself with your quarters, I'll come back to pick you
up for supper." Sirce turned around nodding, the door then closing behind him,
he exhaled as he sat on the bed, he knows there some people that would not,
complain about this predicament but that's just because they have nothing to lose,
and Sirce now has to think about how all those things might change.

=== NOVENTON 

The butler continued into Meldoa's room, the butler ashamed of the mess she has
created, a giant mess that he isn't going to hear the end of especially from her
father, but he never imagined she would actually do it, indeed he has listened
to her rambles countless time of her desires to rid her fathers worry's that 
she will not come into possession of a child.

But to actually do it, has her father actually driven her mad. He knocked on the
door, "who is it," Meldoa said through the door. "Nove'," "Come in."
He continued in, Meldoa sitting at her desk seeming happy with herself.

Nove' knows she won't listen to reason, at least not to the reasons that 
first come to mind for him, indeed Nove' has learned to think differently
about the apes having been forced to work with them in these environments for
so long and while he still holds some prejudices, by and large he mostly consider's
them somewhat equal, a rarity now days.

"milady, I think it would be wise to reconsider what you've done," she exhaled,
"you sound like my father," the butler pinched his brow, "milady, there are
plenty of wolfkin out there who would dream of this moment, why this poor sod."
She looked up at him, "because then father would be begging for a child," she 
configured her hand into the likeness of a gun, "it's supposed to be a threat,
something to scare him with." The butler sighed, "you do realize many would
consider this degenerate behavior," she chuckled, "and what throw out one of the
people he relies on to keep this ship running."

At this point the butler was done arguing, he knew he lost the minute she took 
a different moral stance then him, that moral stance being to shut her father
up at all cost's. "Children," the butler muttered.

"Well, that is all for today, tomorrow I will put him to work, and we'll
see what I make of him," She nodded, "hopefully he's useful," she said with
a smile, knowing full well that her plan was beginning to come to form, now all
that was left for Meldoa to do was to order a pair of engagement rings and make
her threat official.

=== SIRCE

Sirce awoke, feeling grateful for the bed, but spiteful of the prison, 
he wasn't sure how long this whole husband thing was going to last for all 
he knew he would have to act like this indefinitely, he exhaled, he hoped
by then he could form at the very least an attempt to escape.

He slowly got up, putting on his uniform, a simple dress shirt, covered by a 
black jacket with the family crest worn as a necklace. He continued out into the 
main hall where the butler had told him to meet him in the morning during 
breakfast, Noventon he believed his name was, he was still getting used to all the
names, especially of those belonging to the entirely wolfkin staff, which he knew
was small from listening to the banter of some wealthy people, a conversation that
took place when he was just a child.

Sirce exhaled as he walked the halls to the entrance, which was only a short walk 
to the quarters of the workers and servants, then coming across, Nove' who was
dusting some of the railings despite them almost looking spotless. "Ah, Sirce
glad to see I did not need to wake you," Sirce nodded, still feeling a little
groggy as now his entire sleep schedule had changed, although he couldn't 
complain as it had changed to be more in favor with his personal health.

"Now, if you'll follow me we are going to be cleaning the masters quarters,
as well as the other servants rooms, and if the load comes we'll do that also,"
Sirce nodded, despite not knowing what, "the load," meant but he figured he'd
find out soon enough.

"Alright, let's not waste time we only have so many hours to clean." Sirce followed
the butler down the hall into a little room that hoarded all sorts of cleaning
supplies and equipment, "grab a cart Sirce, we'll start with the master's 
chambers." Sirce nodded, grabbing one of the carts, Sirce following him to a
small electric elevator that appeared to be hidden in the wall.

"You'll be using this to fairy things around quite a bit so don't be afraid
to make good use of it, also the weight limit is 500 pounds, don't forget that,"
Sirce immediately understood what the man was insinuating. They then continued
up the stairs up to the third floor, and taking the cart out of the elevator
then continuing down the hall into the master's chambers.

"Seems she took her paper work to bed, explains why she looked like she was
in such a sorry state," Nove' stated, as he made the bed all while Sirce was
walking around the room dusting. Sirce was somewhat familiar with home care
at least familiar enough to the point where he knew what would make you do it
again.

"Ugh, sir," Sirce said, pulling up a piece of undergarment from under a dresser,
"Oh, throw it in the bin, we'll put it with the rest of madams laundry." Sirce 
nodded, doing as he was told, "I'd imagine she'd be more put together," Sirce
commented as he went back to brushing, "I ugh," he then stumbled on his words
once he realized what he just said, "we'd all like to be, to be honest I hated
serving her sisters and brothers more." Sirce exhaled and chuckled a little,
feeling comfortable in the fact that he can lower his guard.

"Is that so," Sirce said with quite a bit of curiosity. "Oh, indeed this ones
just focused on her work the others though are mischievous trolls." Sirce
looked at the butler for a moment, "now when I was young I could keep up with
them but now I'm old and gray and can't stand the nuisance, and this is why I
prefer working for the madams father, and the madam herself." Sirce nodded, "
I assume it's that they treat things more seriously." The butler nodded,
"but I fear Meldoa might treat certain serious things with some childishness,
like." He quickly stopped his tongue, "I believe it wise to stop talking before
I say something I don't mean," Sirce nodded his head, carious but understanding
to why the old butler stopped, he too also needed to be careful of such things.

The two then finished cleaning the madams chambers, not without some more surprises
from Sirce, whom found more woman's cloths as well as some bread that was logged
between the wall and the leg of the nightstand, mold covered as one might imagin.
"I keep telling her not to bring food into the chambers," Nove' said, speaking
like an adult disappointed in there child. 

They then walked past a pair of glass double doors, Sirce feeling the familiar
warmth caressing his skin, he immediately stopped and looked out into it
seeing nothing but weeds suffocating the many flowers, herbs, and other plants
meant to be growing in there place, although Sirce, never really thought the 
plants as weeds they are just plants at the end of the day, 
"does anybody take care of it."  Sirce asked, the butler walked back to Sirce 
looking into the greenhouse, "supposedly," Sirce looked at Nove', "we hire a 
gardener but I'm convinced he  dosn't really do anything," Sirce cocked his brow
"probably should fire him," the butler nodded,  "indeed, indeed, but that is not 
my decision to make, and right now we have no one to replace him." 

A horn then sounded off towards the back of the manor, "oh, thank goodness 
the load here's, come Sirce." Sirce exhaled, disappointed he didn't get to at 
the vary least do something that he was familiar with, but he knew if he did so 
when on the clock, he was sure to attract the ire of those that reside here.

They then reached the small loading dock that was just behind the manor,
a loading dock which provided quick access to the pantry. The butler quickly
found a seat on a create, "after you Sirce, I'm getting too old," Sirce nodded
understanding, but still disappointed that he now has to do this with less help.

The truck then pulled into the loading dock the step to the bed of the truck looking
a little banged up, "oh no," the butler said, seeming familiar with the truck,
it then stopped, and then came back slamming into the concrete dock. The butler
closed his eyes, and exhaled, a few men some are then came out of the truck, some
of them looking tense, with one having what some might say a stupid look on his face.
"Hey guys, what this thing doing here." Sirce then understood the need for extra
air that the butler took, to be considered a thing by a wolfkin, whom obviously
has intellect of a child whom was dropped on it's head would drive anyone to violence.

Sirce then began unloading the truck, with the others, who seemed to have had there
fill today, whilst the idiot was over near the butler talking to him, the butler
having a difficult time engaging in the conversation, a few minutes then passed,
and they had reached some of the heavier boxes that where placed farther into
the truck, Sirce was quick to grab one, expecting nothing of it until his arm 
reminded him of what had been done to it.

He fell to the ground, dropping the crate as a sudden pain came from his shoulder,
he quickly laid on his good shoulder, grasping onto the one in pain as saliva filled
his mouth, as he heard some laugh around him.

The butler was very familiar with pain, he was old after all, and he had a good 
idea of what Sirce was experiencing. "Sirce," he said staring at the poor ape, 
lying on the ground waiting for the pain to subside, he slowly turned to face him.

"Would you head to the greenhouse I think you wanted to do something in there,"
the only thing that the butler could do at the vary moment is give Sirce, some light
work, although the butler knew that what he really needed was plenty of rest, 
and a doctor, but he knew those where tall orders when referring to an ape, 
so indeed the only thing he could do was go light on the poor lad.

The butler then quickly made himself useful, despite his back pain, at least
it got him away from the idiot, and after thirty minutes the load was brought off 
the truck, the old man exhaled as he looked at the three pallets of stuff all cobbled
together he had hopped that, Sirce would be able for this part but knowing his 
condition he didn't want to put farther stress on it, he then thought for a 
moment and supposed he could see if one of the woman or men where willing to 
conduct more dutys, either that or he will be doing it by himself again.

He came down the hall, the one that connected to the greenhouse, looking and hoping
to see if Sirce was alright, what he found was was pretty much half of the greenhouse
floor covered with dirt, and what he hoped where weeds all over the floor, he continued
in straying away from the dirt, trying to keep his shoes clean, and to prevent
the rage of the individual who was in charge of keeping the floors clean today,
he walked throughout the greenhouse a bit until he found Sirce, sitting on a crate 
packing up some seeds, in paper whilst holding his shoulder.

"You do relize I sent you out here with the intention that you'd take it easy,"
Nove' said impressed by his work ethic, but still concerned for his health.
"Sorry, just got carried away," Nove' nodded. "How bad is the arm anyways," Sirce
looked up at him, remaining kinda silent, "I can't fire you, not that I would all
I could just do is give you less laborious work," Sirce then nodded, "sometimes,
I can barely lift a tea cup other times it hurts to pick up anything with real weight."
The butler was certain now he tore a muscle, his rotator cuff to be more precise.
"I heard you got into an accident before you came here, care to elaborate," 
he scratched the back of his head, "a pallet of shit fell on it I got lucky,"
the butler paused. "I see, let's get you cleaned up then, and put some ice on it
I'll put you in charge in finishing up what ever you where doing," Sirce nodded,
and the butler went to find some help.

About an hour later, the butler found his way into Meldoa's office leaving Sirce
to wander around the manor, dusting and cleaning, "how is he doing," Meldoa said
playing with the pen on her desk, as she stared at the papers that laid on it,
"well miss Meldoa, I have no complaints only that he should see a doctor." She
immediately scoffed at the idea, "I doubt that is worth it," "well it might be
good to keep up appearances," she contemplated it for a moment, "nah, it isn't
noticeable," well, he tried. 

"Very well, but I do request that you go easy on him
that arm is easily provoked into intense pain, also I'd rather not lose someone 
who seems to be doing rather well for himself, especially when it comes to gardening,"
Meldoa leaned forward, "gardening?" "Yes milady, gardening, I don't know much of it
myself but he seems confident in what he's doing, not much harm he can do anyways
the bed was overrun with weeds." She paused, "indeed, well if he is any good
we can finally get rid of that useless wolfkin," "indeed, madam." There was then
a pause the butler wondering if he should press her once more into abandoning
her objective and just making him a servant.

She then opened a drawer, pulling out two box, each containing engagement rings,
"Nove', tomorrow I will intend to put my plans in motion," she looked at the butler
with a mischievous smile, "I'm putting you in charge of insuring that we are 
served tomorrow," Nove' was now certain there was no talking her out of this
so he decided to go for the next best thing her father, "understood, milady
I will see to it, now is that all." Meldoa then opened one of the boxes,
and lifting up the ring contained inside, "yes, I believe that is all."

The butler then continued out, skipping past his dutys that where once at the
forefront of his mind, instead slipping into his private room, picking up the
telephone that laid inside, "hello," a voice sounded off from the other side,
Nove' immediately remembering who it belong to, "hello, Dianna, ugh may you be so 
kind as to route me to Junias residence," "oh, yes, right away Nove'." Nove', then
waited a few moments before he heard Junias's voice on the other line,
"yes," "master, it is I Nove' I wish to inform you of a development at the manor,"
Nove' heard Meldoa's father lean forward, "your daughter has recently gotten into
some mischief, and um is threatening to marry an ape whom was recently forced 
into service in the manor." He heard his master stand, "*WHAT!*", what indeed
the butler thought to himself.

"I'm going down there this instant," oh, we can't be having that, "master, master 
please listen," there was then silence on the other end, until he heard his master 
sit, "continue, Nove'," Nove' exhaled, "sir, your daughter was beginning to become
overwhelmed by your persistent request to bare child, that she has decided to act out
in this manner," he then heard his master exhale powerfully over the phone,
"I have been quite pushy haven't I," the butler nodded in silent agreement.
"I also recommend you don't run into this mess like a bull, your daughter is rather
stubborn and I'm afraid she'd do something rash, plus she'd know it was me right away,"
he heard his master then readjust himself in his chair. "why are things like this,
she's the only one who hasn't been a handful and now she goes on and does this," the
butler smirked, "the quiet one does seem to be the most troublesomely intelligent,"

"you mean stupid," the butler wagged his finger despite no one being present,
he enjoys talks like these allows him to get away with acts of judgment without
getting so much as a glare,

"being intelligent doesn't mean one is socially," the butler heard a small
chuckle,

"here, here to that, is that all,"

"I do believe so, sir."

"then farewell, and make sure she doesn't do anything more stupid until tomorrow,"
the butler then hung up, and brought his fingers to his temples, "children," he 
muttered, "always giving us two headaches," he then continued out, and searched for
Sirce to tell him to get some rest, because tomorrow for him would be most harrowing.

=== THE NEXT DAY 

=== SIRCE

Sirce awoke, and although his bed was comfortable, still he wished he was back in 
his apartment at least it would be a place where he felt safe, instead of being surrounded
by wolfkin strangers, he then got up, looking at his pocket watch, I wonder if
I'm ever going to get my personal belongings from the apartment, he exhaled, probably
not, Sirce then got up and got dressed, heading out to the dutys board to see where
he was placed, he then quickly saw that it was in fact his day off, hmm that dosn't make
any sense he thought, pondering if it was a mistake, he figured they'd be working
him for at least a few consecutive days just to get him used to things.

He shrugged, all well, looks like it's the day off. "Sirce," he heard the
butler from behind, Sirce quickly turned around and straightened himself, causing
his back to tense up in pain as well as his shoulder. "Ow," he quickly yelped silently,
"Meldoa, plans to have lunch with you, and I've been tasked with preparing you an 
appropriate suit," oh, Sirce thought to himself.

"Lunch," Sirce said, "indeed, she uh, has her reasons," Sirce knew what the butler
was referring he knew it because that was his only stated purpose, to be the puppet
husband of a wolfkin woman, everything else like his new job, and his pay where
probably only done to keep him in check under his own will.

"Are you ready, Sirce, uh, I mean sir," Sirce cringed at the mention of him being
a sir, it's not like he earned it with the butler, which was an odd thing to think
considering he's a wolfkin and he's an ape, "umm, you can keep calling me," the
butler immediately shook his head, "I do prefer the name Sirce in comparison to
the title, but if I don't the madam will be greatly displeased with me," Sirce
nodded. "Where to," the butler turned to the door, "after me, sir."

Sirce then followed the butler into a dressing room, "I'm also supposed to take
your measurements for other wears," Sirce tilted his head, "can't I just use these,"
the butler shook his head, "Meldoa wouldn't marry someone of poor birth, unless there
was a certain fantastical circumstance, plus if your husband was walking around
wearing a servants dress many would think that she had used her power in unsavory
ways," Sirce squinted his eyes at Nove'. "But she did," the butler stretched the 
measuring tape, "indeed. She. Did, but I recommend not bringing that up."

"Now disrobe your overcoat, I need to make sure my measurements are accurate,"
Sirce did as the butler said and the butler quickly began taking measurements,
"your quite slim," said Nove' who was going around the waist, "yeah, my mom had
to sow a good portion of my pants waistlines tighter so they would fit properly,"
the butler nodded, "hmm, I assume you came from a good upbringing then." "Yeah, I was
an only child," the butler raised an eyebrow, "only," "yeah, my mom lost her ability
to conceive after I was born, so I was given a lot of attention, and all the work,"
the butler chuckled, "I see."

The butler then stepped away, and opened a drawer, "and where did you learn to garden,
from what I understand your last name is Carpenter," Sirce nodded, "blame my mother,
I still know how to work with wood, just gardening is kinda my forte," Nove',
then took a prepared suit from drawer, bringing it to Sirce, "well sounds like 
your well rounded, I'm surprised you got stuck with warehouse work," Sirce 
shrugged, "wolfkin don't take kindly to me," Nove' then exhaled, as if remembering 
if he had forgotten something. "of course, you'd think they care more about 
money," Sirce laughed, "apparently not," the butler then gave Sirce his suit.

"Now then I'll leave the room, knock, and call my name when you are ready, and I'll
share the rest of what is to come of today with you," Sirce nodded and Nove'
left the room, Sirce then began to change, and thoughts began pouring in he didn't
think the work was bad, in fact it was quite easier on his body, and he partially 
enjoys his supervisor who seems to look at him as an equal, the pay was comparable
to his last job too, however he would enjoy some time at his private residence 
obviously he still didn't like the fact he was forced here but he has soften 
to the prospect of it, still however being force to display himself as ones husband
did not sit well with him especially since it's a wolfkin where he knows she'll subjugate
him to her every whim, he remembered what she said when it came to both marrying and bearing,
indeed the last thing he wanted for himself and any potential children, 
was to be held down and raped by some sick woman.

He then knocked on the door and Nove' opened it. "ha, there, any bagging, no, Hmmm
just around the cuffs, oh, nope too long at the skirt, the butler then took some pins
out of his pocket and brought the overcoats waist up a bit." He then stood back,
"that should work," he then exhaled, "are you her personal tailor," he stook his
head, "good heavens no, I had to leave yesterday to get advice in the city, I do hope 
this holds up." 

Sirce looked at him with pity, "does she just dumps things on you," the butler
paused for a moment his eyes darting into the corner of his eyes, "usually no," he then leaned
for inviting a whisper, Sirce accepted, "in all honestly she's better then her siblings, but
this latest event has put me over the edge," Sirce stepped back, "oh," he then nodded,
"well then let's talk while we walk."

They then set down the halls to the dinning hall, "her father is supposed to be
coming today, which is why she expedited this, she actually wanted to slowly
trust you with your position, but he immediately went into talking about her finding
husband last morning and it set her off," Sirce closed his eyes hoping that whatever
the father does, he doesn't blame him, and that he mentions nothing of a child
to this implosive bitch, opps, he can already here his mother a mile away.

"Now Sirce do you know anything of etiquette," he thought for a moment, "manors,"
"oh, um, hands off the table, speak when spoken too... Eat whats in front of you,"
the butler then exhaled, "well it's clear you have an understanding, but you wont
pass we will stick to introductions, if anything weird happens I will pass it off that you
did not sleep well last night," Sirce nodded, and Nove' then opened the door, "we will continue 
with proper etiquette once this passes."

The two then continued in, Meldoa sitting at the other end of the table with a grin
on her face, "good you've finally arrived, I apologize for the sort notice of 
all of this," Sirce felt that the line wasn't fully directed to him, and wish she 
was at least somewhat as sympathetic as the butler, Sirce quickly found his seat
at the other end as it seemed like the most natural position, including that it was 
the farthest away from the witch that kidnapped him.

"Well then, Sirce do you mind if you greet me," Sirce stared at her for a moment,
"hello, Madam." Sirce was not in a good mood, and it poured through his words,
and actions, indeed his body and mind spoke from the heart and he knew it, and he 
knew it would probably get him killed in this place.

"My, my your either trying your best to insult me, which is cute, or I seriously 
overestimated your intelligence," the butler sensed the rising hostility and 
that no party in the room was preventing it, he sensed that Meldoa wanted this 
for some reason, "I don't think the dockside has the qualities your looking for then."

The butler saw, Meldoa developed a short and subtle grin, she's treating this
like an outing to a party, reading his emotions, evaluating his inner person,
every word an attempt at testing him, he exhaled, don't play ball with her Sirce
you don't even know what this world is like, she'll tear you apart, just play 
dumb and smother your hate.

"C'mon can you blame a woman for wanting a rough and tough husband." Nove'
felt the hate emanating off of Sirce the kinda hate that was uncomfortable to
sit around, "if only that where true," she rested her hand on her chin.

"Very good, keep going like that you might end up with one of my
garbage thrice removed relatives, hmm no that would be a waste, we won't keep it at one" 
she chuckled at the last word, and annoyingly fabricated chuckle meant to provoke, 
what are you judging Meldoa, Nove' thought almost whispering it to himself subconsciously.

She then got up from her chair and walked over to Sirce, his eyebrows fully down
his eyes hate filled eyes staring her down passionately, there's nothing like taking
away a mans agency to make him like that, Meldoa sat on the table halfway,
she wanted to provoke him knowing he'd be targeted, she wanted to see how 
he would react, how he would respond, gauge how much control she'd have to bring
onto him in events like these, so far there's hostility but that's to be expected,
whats important is that he knows where he is and whether he's actively controlling
these emotions or not, so far he's doing rather well, not accounting for the banter
of course but everyone needs a little sharp tongue to defended themselves and he
has it, he might not be as clever but he has it.

"your not vary good at self control Sirce arn't you," Nove' silently sighed,
so that is what this is, he pondered while looking at the two, indeed Meldoa
wanted a good appearance when it came to this, the threat had to feel real after all
and she needed someone who was either subservient or knowledgeable enough to know what
was to be done.

"What do you mean by that, I'm just sitting here, like is expected of me," Meldoa smiled,
"expected indeed," yes he needs work, like every new comer would need, but he 
did a good job at diverting his rage and that was enough for her to consider him
fully.

"Congratulations, you won," she said putting herself in arms reach of the boiling
man, she then put the case for the engagement ring on the table, looking at him
for longer then a second, then leaning down to him remaining a sort distance from
is face, "today you'll meet my father, and you'll act like my loving husband unless
you want to end up in a river some where, it's all up to you of course," 
Meldoa was surprised Sirce's anger didn't turn to fear in that moment, 
she knew she had someone mentally strong, it made her ponder for a moment but 
it was just a vapid thought. She then brushed his check with the back of her 
hand, her skin sliding across his clean shaven cheek.

"Now let's eat Sirce, and when father comes play your part." She then signaled
the rest of the staff with a bell, and quickly food began pouring in, he will learn 
to like it here, Meldoa thought to herself as a plate was brought to her.
