== THE KINDLING OF HATE ENCAGED
:autofit-option:

=== SIRCE

Sirce stood behind Meldoa whom sat in a chair, looking at her father
who seemed to be taking everything well, but Sirce knew it was just a front and
that this was in fact his worse nightmare, Sirce felt a little camaraderie in that,
that he was not completely alone in his thoughts.

"Ha, so your my daughter's fiance, it's about time," he said with a giggle that betrayed
him, Sirce looked down at Meldoa, seeing poisonous smile stretched from ear to ear,
"indeed it is father indeed it is," Sirce brought his hand across his chest forming
it in a cup just like Nove' told him too, "my name is Sirce, Junias Ackscene,"
he nodded, "well then welcome to the family Sirce, I hope you treat my daughter well,"
Junias fought the words out of his mouth not that he necessarily hated Sirce, or
wouldn't accept him as a person but at the fact the most stable of his daughters
had actually done the unthinkable.

What the hell are you thinking, Junias wanted to shout but as with anything 
such a public outburst would not reflect kindly onto him, and now at this most
delicate moment in the relationship between the Ternia family, he needs the outward
appearance of the family to be strong. He looked up at Sirce, and decided perhaps he 
can make the unwilling participant crack under pressure. "So Meldoa, how did you 
meet this man, not a lot of humans like to come visit here," he was right the only
time apes actively came here was for an explicit purpose, like a diplomatic envoy,
or because they where forced to by other means, this would challenge the first
foundation of there 'love', how they met.

Meldoa smiled, "he was simply on an envoy trip, made a good first impression,
and we exchanged a few letters, and we eventually decided it was a good time to
do so." Junias leaned forward, it was not hard to tell that he was thinking deeply
Sirce was growing nervous as he thought about what it'd mean if he got confirmation,
that there relationship was a false one, what would she do.

Junias kept staring at the two, this is a waste of time I should just accost her
right here right now, he thought as he leaned back in his chair, "Sirce do you 
mind if you take a step out for right now," Sirce then looked at Meldoa, and she
and he went out the door.

=== JUNIAS

"Meldoa, my daughter, what the hell are you doing," she leaned back and crossed
her legs, "oh whatever do you mean," she said sarcastically, "enough," her father
put on a tone she knew would only spell trouble if she didn't respond properly,
"I've force an ape to become my husband in order to stop you from pestering me."
They both sat in silence, the father exhaled, "in what way was I pestering you,"
she looked at her father disapprovingly, "oh, I don't know the blind dates, the 
weird meet ups with members of the opposite sex, the talks about artificial 
insemination," Junias pinched his brow, "Meldoa, I am looking out for you, for the 
family," Meldoa's face contorted, "oh really, well how would you like if you where
told, by your father, to have sex with some random girl you just met," Junias
stared at the floor for a second. "Listen, I am... If your going to be come head
of this family, I want you to at least to have child... I need to make sure that
your legacy is preserved because the minute you enter my spot there will be 
people who will challenge your claim," she spoke slowly so that there would be 
no room more misinterpreted words, 

with him pausing every so often to collect his
thoughts, Meldoa remained firm in her expression of anger.

"Really that's what this is about a linage, I understand my responsibility's,
but to be treated like this by my own father is disgusting," Junias felt a wound
produce itself one his soul, "Meldoa, I," Meldoa gripped the chair, "I hoped, 
you'd at least respect my agency and my ability to determine when the time was
right, and whom was deserving enough to receive that right," her father then 
looked off to the side of the room, feeling a coming onset of guilt,
"but clearly that's not the fucking case," Junias remained silent,
perhaps I have made an error, he thought to himself, perhaps I have been too 
hasty. 

"I'm sorry," Meldoa scoffed, "he will stay in my midst for the time
being," Junias picked up his head, "Meldoa," she then brought her knuckles onto her 
chin, "I have no reason to trust that you won't continue your assault, he will
stay, and if you continue your actions I will bear his child."

Junias understood all the implications of this, how this would send shock waves
though the wolfkin population, how the daughter of a wolfkin elite, produce a
mixed child, Junias shook at what could happen to the family if he kept her
in the fold and what it would mean losing her.

If she disguised as an elite it would seem like the marriage was completely
political, he could arrange a few shell companies to be made, do some fake
exports and imports that are favorable, as long as no child was born people
would scoff but they would understand, "your supposed to make my life easier
you know," she folded her arms, "you to," he closed his eyes, he knew he was in 
no position to decline this either this is her house and these are her rules.

"I'll support you in this endeavor, and I'll stop harassing you, just don't
conceive a child." She smiled, "thank you for coming to an understanding," he 
nodded exhaling, "anyways lets finally get back to talks about everyone else's
financial situations," Junias crossed his fingers hoping that the rest of his sons
and daughter have decided to be kind to him this year.

The talks went on until it was time for supper, something Junias was hoping to 
be able to avoid, as he wanted to be home with his wife sharing a meal, but alas
he's found himself here endlessly talking about documents, maybe getting into
the affairs of the elites was a mistake, and he should've just stayed a simple
arms dealer.

"But as of right now I think an expansion is due in our jewelry business, seems
foreigners have taken a liken to our wears," Junias nodded, "careful, we don't 
want to be caught in a fad," Meldoa nodded, noting the concern, 
this is why Junias likes Meldoa articulate, precise, she knows her way around 
sure she isn't a sweet talker, but everyone upon meeting her knews why 
she's where she is.

Junias then leaned back in the chair, letting his worries dissolve his children
make him so stressed, yet Meldoa can manage it all, he didn't see her as this 
super woman of course, but it was nice to talk to someone on his level when he 
got stuck up on something, instead of the conversation boiling down to excuses,
and misunderstood jokes, indeed Junias felt like an island when it came to talking
about anything.

"Carnis's business have been running in the red as of late," Junias leaned in,
"any reason as to why," Meldoa looked at him. "He thinks he's getting sabotaged,
of course there could be other factors as well but he believes someones tampering
with the materials," Carnis business deals with cleaning supplies, acids, and
other chemicals and materials related to scientific resource they also have a 
few agreements with collages for materials, but there most lucrative business
is saltpeter, and guncotton. "Which side of the business," Junias asked,
"I pressed him, our arms chemicals," there was then silence in the room,
"how long has this been going on."

Junias was now getting frustrated, as Carni should know by now that he 
should be letting people know about manufacturing issues of this matter,
"for a few months, I already put Its'van on the matter he's digging through,
Carni's mess as we speak," Junias became only slightly relived by the fact
but it was still concerning, how many loads of ammunition where sent out in that
time, who did they go too, for all Junias knows the entire supply chain 
could be compromised with bad powder.

"I'll send a strongly worded letter to him, about this," Junias said as he rested
his head against his hand, "it's probably the Terina family too," Junias exhaled,
"is Its'van also looking into where those compromised shipments went," "yes,"
Junias nodded his head, "I'll send more men down there too, discreetly of course,
also give me regular updates on the matter."

Junias looked at the entire stack of papers they had just gone through,
"is it over," Meldoa nodded her head, "I believe so," Junias knows that the 
matter revolving around the Ternia family is elevating his emotions it's not that
it's making him irrational more that he can't tolerate mistakes at this point
and how can he.

"What time is it," Junias asked, "6:30, father," "then I suppose I shall be staying
here for supper," even through Junias knew it, saying put a dagger in his heart
and with this news coming in he wished he could just appear in front of his
wife and share a meal with her, at least it would temper his frustration.

"Alright then Meldoa, I'll see you in the dining room, do bring your 'fiance'
if you desire," Meldoa nodded with a smile, "of course."

=== SIRCE

Sirce was glad Meldoa let him leave the room, the air in there was suffocating
with that man in there trying to choke every single detail about his current
situation out of him, Sirce, then place a once potted flower into planter box,
bringing the extra soil over it's root and gently patting it into place. That
should do it for this section, he thought as he want to clean up the floor before
a maid came in here to berate him.

And after a few minutes of cleaning Nove' came into the greenhouse, looking around
for a few sort seconds, "well I think you might put that wolfkin out of business,"
he said sounding genuine, as he looked at one of the flower boxes he just worked
on, "I doubt it Nove'," the butler exhaled, "trust me that woman is unbelievably
unbiased when it comes to money," Sirce smiled, "so she's biased towards money"
Nove' produced a smile from the smart ass remark, "indeed so, oh, Meldoa is requesting
you for supper," Sirce exhaled, "damn witch," he muttered, Nove' nodding, as Sirce
stepped away and charged ahead of him.

And after a short distance Sirce, as well as Nove' soon found themselves at the 
front doors of the dinning room, "there's already a plate on the table for you 
sir, you may start eating once your seated," Sirce nodded, as Nove' opened the 
door for him, Sirce nodded as a way of demonstrating thanks and continued 
inside, Juinas sat across from Meldoa, Meldoa only looking up for a second,
whilst Junias continued to keep watch of him, Sirce felt unsure what to make of 
this was he, protective of his daughter, or was he trying to measure what kinda
man he was.

Sirce then sat next to Meldoa as that was where the plate was placed, although
he would've preferred to sit next to Junias, or even better all the way across 
the room, actually the breakroom with Nove' would've been the best choice but
that wasn't going to happen in this situation.

Sirce then quickly went about eating his meal, "so, Sirce I heard that you like
to garden," Sirce nodded, "picked it up from my mother," seems everything
had boiled over well, Sirce thought, to be honest he was relived but also,
kinda disappointed that her father hadn't figured it out.

"Ah, so your mother likes to garden, how vast is hers then," "pretty vast sir,
and when I left an addition was being put on," Junias smiled, "well I suppose 
I should make a visit, it's been a while since that greenhouse has looked right,"
Sirce nodded, well at least he's making small talk probably to prevent pissing off
his daughter.

"But I would like to apologize for my daughter's behavior, plucking you out of a
warehouse like that I'm sure gave you a rather sour impression," oh, the word 
carried a certain unsure quality in his mind, is everything okay, was he going
to be let go, if so he hoped it was from the marriage department, he didn't mind
servant work.

"Nove' can you fetch his pay records," Sirce cocked his head, what is this all
about he pondered, Nove' quickly exited the room, Meldoa developing scowl soon
after, "excuse me," she said with great offense, the father then sighed.

"Meldoa, he may be your butler but he and I both understand this situation is
less then desirable," she scowled both at the door, and at her father, "so tell
me Sirce how do you feel about this situation," Sirce then looked at Meldoa
who seemed to be staring knifes at him, "I'm being treated well, however like
any prisoner I desire my freedom," Junias nodded, "a fair assessment,"
Nove' then came in and placed a folder onto the table in which Junias then
began to search through.

"Ah, here you are, Meldoa," he spoke with an exhaled. "your asking him to be 
both servant and fiance, at this pay," Meldoa seemed glare at here father,
"he dosn't need to know that," he shook his head, "your inviting this human 
into your personal affairs you need to at least pay him well, least be it
someone else does," Meldoa quickly stopped glaring and stared at her plate.

Junias then took a pen and scratched out the original wage, "fourteen dollars,"
he said, "what, no, that's more then the others," Meldoa spoke as if insulted, "and
are anyone of them your fiance," and she quieted herself once more, Sirce 
developed a smile, seeing the witch left in a state where her protests where 
meaningless and her authority was overshadowed by another.

Although this talk of wages, hmm, why indeed did his wage seem so high compared
to every other place he looked at, I mean there was an obvious trend, I mean 
it was just a few cents but a few cents is a few cents, no matter who it came
from, and the hours, they where also more favorable, why there had to have been
a reason.

But of course Sirce wasn't skilled in business or social affairs, or even 
history, however he had his wits, and the logic he inherited from math but
when someone doesn't even have the concept of an incentive structure, it
becomes hard to find how everything comes together.

Sirce then let the problem go for now, it still stuck in the back of his head
however trying to figure out why it stuck out of him, of course he knew why
he picked the job, and he knows why other people picked the job, but these
people talked about it like it was really important, why, was it too take from
other business's no that only just a small piece.

Sirce continued to attempt to wrap his head around it but like any new problem
solutions where numerous and full of holes, however across the table, Junias
gazed had drifted over to the man who had grown still, his eyes fixated on some
random immobile spot on the table, he recognized as something a thinking man
would do, Junias wondered whether his daughter had truly picked out a dock worker.

"Sirce, you seem to be lost in thought care to share anything," Sirce was then
knocked out of his trance, looking dazed for a few seconds, "oh, uhh, no it's 
nothing," Junias rubbed his chin, "are you sure," "yes, I am." Junias shrugged, 
wondering what the man was truly thinking, but secrecy doesn't necessarily mean 
anything, well it could mean anything, so Junias decided to let sleeping dogs lie.

Sirce for some reason felt stupid, he felt like the what he was asking himself
was so simple, yet it eluded him. "So, Meldoa I have a question for you,"
she perked up all while Sirce was fighting to keep his thoughts restrained so
he could keep up with the conversation, "ask away, father," "well, are you 
planning on taking him to the Serisca ball, "Meldoa thought for a moment, "perhaps,
it would tell everyone that I am currently taken, it will certainly keep those 
minor family's away from me, and maybe it will provide the illusion of foreign
backing without me uttering a single lie," her father smiled, "hopefully that
is the case."

A ball, why the emphasis again, why is it sticking in his head, Sirce was beginning
to feel like his head was going into overdrive, so much so the entire room seemed
to move two thirds slower then it was actually going at. He then heard a knock 
at the door, and so did everyone else, as they turned there heads to it.

Nove' quickly went over opening up the dinning room entrance by just a hair,
until finally opening it up fully, Junias arose entirely in shock, but despite
the initial reaction seemed genuinely happy at who had come to visit,
indeed that every person was his wife, "Violy, what brings you here, I thought 
you where going to leave us to our business," not that he was complaining 
"I did say that didn't I," she said with a smile that reminded 
Sirce of the woman sitting next to him.

"and you also said that you'd hope it wouldn't be long, but I cannot blame you,"
she then looked at Meldoa, "our daughter seems to have gone and done something
unbecoming of her," there was a certain quietness that befell the room, "I'm
sorry to ruin the meal, I understand that you might have worked past the issue 
yourself's but could everyone here give us a moment, please." She casted her gaze 
across the entire room, everyone seeming to nod, and exciting understanding
that protesting would've elicited a rather uncomfortable scolding.

"Well I was hoping to enjoy at least a meal with her, it dosn't happen as often
as it used to anymore," Sirce watched as the articulate man seem to slump a
little Nove' patting him on the back, "you'll have your moments Junias,"
"I hope so," he responded, Sirce smiled a little at the sight, kinda being remained
of his own parents back home, making him forgot for a moment the situation he was
in, "now she's probably going to take a while, scolding her," "tea in the drawing
room sir," Junias scoffed at the idea waving his hand away, Nove' brought his eyes
to Sirce, and then Junias did as well.

Sirce would've preferred having the garden to himself, he discovered that no 
one really ventured out here, most likely due to the heat, but it had somewhat
been a cloudy day and it had cooled to a reasonable temperature, which lead
him having to the share the room with Nove' and the head of the family Junias
as they ate crackers, and sipped tea, whilst having a wine bottle under the table
in the event they ran out of first beverage.

but the only reason he would preferred being empty, was because he could feel 
the judging stare from Junias, it didn't belong to that of a wolfkin who was
disgusted at the mere sight of an ape, it was more like a craftsman contemplating the use 
of a tool, but Sirce would not be surprised if it was the former, as he was getting
glares all the time from his 'coworkers', he thought he had grown used to it but little does one 
realize the tax of it when there is no oasis of fellow humans.

Sirce worked while the two talked, finally cleaning out the last of the garden
beds that had over weeded at the front of the entrance, something that he decided
to work towards when he first came here, now all he had to do was prepare for 
the second phase of rehabilitating the greenhouse, which was cleaning and planting
out the middle section, he then exhaled as he looked out to it, it really was the 
first time he had done anything like this himself, as his mother was the one mostly
managing the establishment he was just someone who did the ground work, he thought 
of course he was doing quite well, but he was sure his mother would find things
he could do better. "Sirce, come join us you've been working the entire time 
we've been here," the voice came from Junias, Sirce turned around and looked at
the two seeing that the wine bottle had preemptively come out, Sirce then looked
back at the garden, "Sirce, come." He said it in a way of a master coaxing his
dog, something, Sirce wasn't found of. He gritted his teeth, knowing that it
didn't matter what personal preface he had for his time, but what the head master
had in mind.

He sat down with the two, Nove' pouring him a glass of tea, "Nove' what's with this
at least give the lad a good drink," Nove' then looked at Junias, "I do not think 
he has a preference for alcohol, sir," it was true, Sirce gets rather sever nausea,
as well as hives from alcohol. He came to discover that when he was rather young.
Not that he'd enjoyed it to begin with.

"Huh, well I suppose tea would make the better drink then," Junias then stared 
out at the up and coming garden, "well at least Meldoa got someone who can do 
work," Junias said with a laugh, he then leaned on the table placing his hand
against his face, "I assure you sir, she was quite lucky, unfortunately I cannot
say the same for master Sirce," Sirce face slightly contorted at the mention of master, 
"ah, indeed she is, unfortunately we can't really do anything about it, 
well easily, especially as long as she feels strongly about this,"
everyone seemed to sigh, "hopefully, she's talking some sense into her right now."

MELDOA

Meldoa remained seated in the dinning room chair, as she listened to her mother
accost her, seems her entire family has decided to dog pile her today,
but she knew that was going to happen. It always took a certain amount to strain
to tell someone to shut the fuck up. At least that's what she thinks.

Meldoa's mother exhaled, "was it truly that awful, it wasn't like he was forcing
you." Meldoa casted a gaze at here that said yes. "Well then, Meldoa. I cannot 
deny it either, for I too was frustrated, but I think that we can both agree this
is an over reaction." Meldoa shook her head. "Meldoa, you have taken a stranger as
your fiance, not only that but he is an ape. I understand, that your father 
prefers not to call them that, but that is what they are." Meldoa sighed.
"I know who he is. This wasn't just some rushed decision made in the span of a
second. I have watched him for some time, I know he likes shopping on his day 
off, prefers fresh produce over canned goods, he helped a local butcher with some
of his business with us, the only thing I was surprised about was his affinity 
for gardening, as all I knew was that he also enjoyed the part and it's flowers."

Her mother adjusted herself in her seat. "Well then, I apologize for assuming
anything less of my daughter. Still however, he doesn't belong here." Meldoa
leaned against one of the arm rests of her chair. "Indeed, he doesn't, but 
we both know I'm not just going to let him go, because you and father tell me 
so. That's only going to happen when I no longer need him." Her mother
scowled. "And when will that be." Meldoa smiled. "we'll see, maybe it will be 
tomorrow, or a few years from now, the point is I don't think father's learned 
his lesson." Her mother continued to stared at her an obvious look of objection
possessing her. "Listen, I understand we've given you a certain level of 
independence, but is not how you should use it." Meldoa sighed. "We might as 
well get father, and finish our now cold meals together." Meldoa's mother knew
what she meant when she said that, that this conversation was going to go nowhere
but circles, she arose from her chair.

"No, I believe I'm going to go home for today. You've made it far more eventful
then I'd like." She then continued out the door leaving Meldoa, alone in the dinning
room.

SIRCE

"And then there's the family they keep breathing down our necks." Junias was now
well and drunk. Sirce, and Nove' looked at each other as the once calculating man,
was now sprawled out onto the small table. "Seems he's had a lot on his mind."
He said, watching the man he calls sir, cry. "I know it is unlikly but, 
Remind me not to end up in his position." Sirce asked. Nove' nodding, 
his wife then entered into the garden, looking around the new scenery until 
bringing her eyes to her less then sightful partner. "Oh, Junias." She muttered 
out of pity, slowly walking up to him.

"I'm so sorry," she spoke to Nove', "it's okay madam, he's obviously been every 
stressed." The woman nodded, as she helped Junias up to his feet. "Yes he's had 
plenty on his mind, to be honest I was sure that he was going to enter one of his
long brooding from the stress," Nove' nodded, "oh my, I would not want to be called
back to service the master just to deal with that." They both nodded, as she 
began carrying him out.

Nove' then exhaled, "I'll ensure to ensure that next time it's just the tasting 
wine," he said as he put the cork back onto the empty bottle. "Well, Sirce, what 
do you think of the family." I shrugged. "Just like any other." Nove' laughed.
"Indeed, Sirce, indeed." We then heard the steps of a woman the gental clacks 
coming from the door, and echoing into the greenhouse.

"Is father still here, I want to say my goodbyes." Meldoa stated, Nove' shook
his head. "He was dragged away by your mother, in a rather drunken state I might add."
She exhaled, she then looked down at me quickly finding a seat and bringing it
to the rest of us. "Are you here to berate us milady." Nove' asked, seeming somewhat
amused by Meldoa's, expression of anger. "Well we can skip that part then."
She said as she looked away. "But now that I judged you for myself Sirce, I believe
I will keep you." I look of disappointment went across Sirce's, face. "However,
fathers correct, I do need to treat you properly for the service you provide,
but just so you know I will reap every bit of value out of you." The words 
made Sirce uncomfortable, he knew it could entail anything within these walls,
and the only person who could defend him has his hand tied.

"Meldoa, I think you should go light on the intimidation I believe it'd be better
if we treated..." He stared at Meldoa as she stared back at him angrily,
"very well, miss Meldoa." She then locked eyes with Sirce, "if I refuse."
"You mean if your uncooperative, cement and swimming lessons are cheap you know."
Nove' sighed. Sirce knew how much wolfkin valued the lives of man, it could be 
the most obvious, cleanest open and shut case imaginable, and nobody would be 
charge, it was only when everyone was angry enough when something happened.

"Then I guess I have no choice." Meldoa nodded. "Indeed you don't." There was 
silence and Nove' looked at the two of them with concern. This is going to turn 
into a mess, he thought. "But let's put that aside and focus on business, here
I want you to take the job of the grounds keeper and since your the only one 
Nove' will be handling your budget and expenditures, but your moneys yours,
second you will act as my husband." "Yes you've told me that." She shook her
head. "But I haven't told you the responsibility's, you'll come with me, during 
balls and meetings I consider advantages, because although you are an ape your
presence can merely invoke the thought of foreign support." Sirce tilted his head.
"And why is that so important." He asked, she smiled. "Because Sirce, you try 
raiding a factory, or hitting a vehicle halfway across the globe, and besides 
foreign money can have it's advantages as well."

Sirce thought for a little bit. But they all hate us. "Won't they have a distaste
for your new found 'ally'." She nodded. "Some will, but they all know that 
the nations of the newlands are prime for profit, even if they are no longer 
under wolfkin control." Sirce them remembered the revolt and the resulting
twenty year war, one that took many lives, how he wished it happened here in this
moment.

"So I will have you trained in our ways, in order to sell that illusion, but 
even if it fails you'll always have other uses, but first we'll go over our plans."
She then poured herself some tea. "In a few weeks I will have a meeting with
a representative from the newlands, well he's more of a business tycoon, but that's
neither here nor there. Anyways I want to secure some written agreements from
him, and I figured you'd help break a little bit of the water." She then took
a sip from her cup. "There is also that ball I'm sure you heard it referenced
during our meal, it is a very important political ball and I want you 
to partake in it." I exhaled, this sounds like it's going to be a lot of work, 
between managing the grounds, and trying to play political husband to this 
crazy bitch.

Sirce exhaled. "Oh, come on now I'm sure there are plenty of people from your
little enclave that would kill to be in this kinda position." Sirce looked down
at the floor, and with out a thought. "I just wanna die quietly you dumb bitch."
The words left with no effort, like they where a secret thought bubbling up 
inside. "Well, that can be arranged." Sirce jumped up. "Wait, wait, wait, you
know what I mean by that." Meldoa chuckled, as Sirce panicked, and then exhaled
with great relief, Nove', shook his head at the woman's poor taste of humor.

"Well then, I believe that's all we need to discuss, so lets get to work people."
She said as she clapped her hands, then throwing a glare at Nove'. 
We both sighed as she ventured off back into the estate. "Well that went better
then expected." Nove' said, as he picked up the tea. "I was expecting an ear 
full but perhaps she decided it was not in her best interest." Sirce nodded.
"I mean you are her best man, are you not?" Nove' smiled. "Indeed I am." he 
said with a chuckle, and continued out of the greenhouse.

Sirce then stared out into the greenhouse, not looking at anything in particular,
just the events of today flowing through his mind, a lot of things have happened
today the reach of such things have yet to be seen, but he can tell he's going to
play a major roll in these peoples plans, whatever they may be. The problem is 
that Sirce feels helpless against them, every time he tries to reason what they
mean, or how there decisions will impact everything he hits a brick wall. Ignorance
is a sin and this is his greatest one of all, and now Sirce is only left
with the hope that he'll maybe someday have the knowledge to fight back against 
his captor.

THE NEXT DAY

"Sirce straighten yourself." Nove' said as he pressed his hand against his lower
back. "Whens that harness supposed to come in anyway." He asked, as he rubbed
his back as it was sore from being in the same position for too long. "Tomorrow,
sir, I'm afraid your going to have to cope with my dialogue for now sir." Sirce
sighed, and although he was annoyed, he knew better then to direct it at Nove'.

Recently, Sirce, has been feeling the heat in terms of responsibility's being laid
upon him first was his training into becoming what was expected of someone of high
status, then there was the rehabilitation of the manors landscape after it was 
left in such disrepair from the previous ground keep, and then appealing to the 
wit-, considerate wife. Sirce was trying to learn to be careful, he didn't want 
anymore slip ups. He looked to the corner of the entry way seeing a maid, Elizsha
is what he believed her name was staring at him in a prideful disgust, oh and his
colleges. He really shouldn't use such a word for they where to separate peoples
in the same building the only reason why they had not done anything to harass the 
poor man was because Nove' knew how to keep them inline and the madam didn't want 
any incidents, that as far as Sirce knew he was protected by Meldoa. Sirce assumed
the latter would be a running theme no matter who he met.

"Nove', I'm fucking exhausted." Sirce said, he looked at him with the same tired
eyes, it really had only been a day but it was not, that they both knew that this
farst was only just the beginning and there bodys where only just preparing them
for the exhaustion. "Now, master Sirce, watch your tongue." They both exhaled.
"Also, master Sirce, do you have the estimate for the redo of the manors lands."
Nove' was originally was suppose to take charge of that, due to Sirce being an ape,
and having limited knowledge of math, but Nove' knew better and was aware just 
buy looking at the paper Sirce used to figure out how many plants would go in
each box that Sirce was capable of the task. "That's going to take a while Nove'"
Nove' nodded. "Just finding an excuse to go into the greenhouse to sit down." Sirce 
nodded. "I think that is a fine excuse." Sirce said, beginning to walk to it's
double doors.

"So how serious is this ball anyways." Sirce asked as they walked. "I'm sure 
you heard that this one is a little more political then the rest." Sirce nodded.
"Well the five major families are going to be there, as well as the number of 
minor families, and middle family but thats typical what really makes it special
is that you are not going to be the only human there." Sirce snapped his head 
to Nove's, he always thought wolfkin high society was very exclusive he figured 
that from when he first came here, but why now. "There are part of a collective
diplomatic expedition that are going through the continent, the nations are solidifying
there independence from us, not that they weren't already, this just drives the point 
home." Sirce cocked his head. "That's not the point however, what is important is
that we want what what they have, so making a good first impression is key." Sirce 
thought for a moment, independence is to act on behalf of oneself, so there send
envoys upon there own behalf, okay that's simple. "So that's why this is so 
important the war caused an expulsion of the wolfkin family's, causing them to lose
out on resources and profits, and defunct there investments into the newlands,
and some are hope to recoup and others are hoping to steal." Nove, smiled.

"Yes, but also imagine this, formulate enough trust with the human nations,
and you might just end up with a monopoly on diplomacy, who gets to see 
who and who gets to get what." Sirce nodded. "But wouldn't that mean Junias
would have to be a neutral party." Nove' nodded. "To an extent, depends on the 
incentives." Sirce was still growing in his logic, he ran a few thought experiments
the night before, and even read a few old news papers as he figured they might
hold significance, still things seemed to elude him. He wasn't used to politics
maybe if he gets the money he can get some books about it but right now he will
have to deal with this rough equation he has in his head force + means = will and
if will > others_will then you win so yo speak.

In a way, Sirce sees the world through math, not entirely however it is just a
part of him that his university teacher had beaten into him with speeches and
books, as well as conversations. Sirce began to wonder how he was doing,
he understood that he was only doing it because the university got into debt 
with his parents, but he liked the guy.

"Sounds like you know a lot about this stuff." Sirce said as they arrived at 
the double doors. "Spend some time with master Junias you'll eventually pick 
up a certain portion of the trade I'm afraid." They then made it to the table 
still remained in the middle of the greenhouse, with the three chairs that had
surrounded the small thing. "And it sounds like I'm going to need to learn a
that portion." Nove' nodded. "If you are going to defend yourself yes." Sirce
nodded.

They both sat down, reconstituting themselves. "Heh, if only it was break time
this would have gone well with some tea and crackers." Nove' said as they both
looked into the now sprouting beds. "Sadly, it's not." The feminine voice came
from behind, the two looked behind them seeing Meldoa being accompanied by a maid.
"Ha, Meldoa I assume your here on business." She sat down the maid standing next 
to her. "Nove', I need you to start attending to the vault." Nove' seemed
to tense up. "So soon, madem they can't possibly be following through with this
at this time, especially with the ball." Meldoa shook her head. "It will be soon,
I don't know when but soon, there getting desperate my father underestimated his
pressure tactics and there now having the opposite effect." Nove' exhaled.
"SO it's war then." She nodded, and arose. "Alright Sirce, lets get to work 
before work gets to us." Nove' said rising.

## Meldoa

Of course things just had to end up this way, Meldoa thought, but she could not
blame her father as she knew the situation was balancing a piece of pasta at the 
end of ones finger. A raid happened last night at least that was what she was told
and some of Junias's own men grew angry and went out to draw blood hitting some
major depots in other words, a cold war just went a little hot but things 
could get worse soon. All this could happen before or after the ball so Meldoa,
has been business making phone calls and arranging travel for the children to
her residence, while the parents go to there own private villas.

Some might see this as a way to easily pick off all the children, and indeed it
did come at some risk, but spreading out ones resources came at a great risk,
and children are the greatest little risk takers. Besides it is the best to leave
them in the care of some one who knows every single one of them well.

"Madam, why are we forced to cater to that ape." Meldoa sighed, she has been dealing
with these complaints none stop since she made her intentions clear on bringing 
in Sirce. "Silence Piltra, it is none of your concern." The maid immediately 
silenced herself as she followed Meldoa, but it was easy to tell she still
harbored resentment over the fact that this ape has climbed the latter essentially
overnight and now shes forced to cater to him, Meldoa scoffed a little to herself,
little does she know that this is his prison. She thought, as they approached the 
office again.

Eric, Tarter, and Vesina should be coming here within the hour, the rest however
will be in the following days. She exhaled as she sat at her desk picking up the 
phone. Honestly why does anyone dream of having this job. She thought as she waited 
to hear the operators voice. "Yes, operator put me in to the Junias residence line."
"Right away miss Meldoa." The operator said, and a few moments later she heard 
the phone get picked up. "Is everyone moving." Meldoa's father asked. "Yes, there 
all making preparations as we speak." He exhaled. "This could've gone better, if
I could've foreseen." He paused. "No, no one could've foreseen that." There was 
then a period of silence. "Sorry Meldoa, it's been a long few hours for me."
"I do not doubt that father, is there anything else." "Yes, I'm sending more men
up to the residences, yours in particular will be receiving extra support, also
for now where holding out what ever happens we don't want to appear as aggressive
or the aggressor especially before the ball." Meldoa nodded. "Indeed we don't want 
the other middle family's feeling threatened and joining in if and when things 
kick off." Meldoa then looked at the paper work. "Do we have an estimate for how
much this going to cost." She heard her father adjust himself. "last time it was
a light skirmish, this time I think this will be a genuine war maybe the high familys
will get involved if things get too crazy." Meldoa exhaled. "That's something 
we certainly don't want." "Indeed, they'll most likely side with the already 
established family." Meldoa then remained silent for a few seconds.

"I'm not so sure they have been rather erratic recently." Junias then followed
suit with the silence. "I have considered this possibility, which is why your 
little endeavor has given so much of a headache." Ouch, Meldoa thought,
maybe she could've had her outburst after the ball. "Either way he will 
serve his purpose at the ball in order for us to gather ape support." She heard
him adjust himself, exhaling. "One can only hope." Meldoa gritted her teeth a
little. I made my plan, it will work despite him being of common birth.

"Well either way I don't think it has effect there opinions of us that much,
at least in comparison to our current circumstance, so as long as we can properly
navigate this shit show." Meldoa nodded to herself, "All right, well I'll get back
to my business." "And I'll get back to mine, love you Meldoa." "Love you too."
Meldoa placed the phone back onto it's holder and got up from her desk.

"Philtra, prepare for our guests, also fetch Sirce when they arrive they will
have to meet him eventually and it will make good practice." Meldoa saw a slight 
scowl in her face. "Yes, madem." "Piltra." She stopped as she turned around.
"If your so much as unprofessional to Sirce, I will see this as a breach of 
contract and send you out of this manor." She nodded without looking at Meldoa
and continued out, people have to make everything fucking difficult shes a good
maid just if she could look past this.

### Sirce

He stood at the doorway as multiple cars pulled up to the front, watching 
as an entire convoy of maid, butlers, and guards poured out of every vehicle.
And this is only for three kids, he thought as he watched then begin to approach
the front, Nove' then came rushing forward standing beside Sirce. "Goodness how 
I wish I could just be a middle manager." Sirce looked at Nove'. "Then you'd
just be an asshole." He shrugged. "So be it, also the children." He said looking
at Sirce with a disapproving glance, Sirce rolled his eyes knowing the drill by
heart.

The kids came shuffling in each one of them giving him strange glares as they 
walked past. "What is an ape doing here." One said, Sirce paid it no mind, best
not to, and once the last child made it safely inside, Meldoa came racing down
the steps. "Hello, children." She said, as she stumbled over her heels a little.
"I hope the drive wasn't to discomforting." She was not even halfway down
the stairs and two kids tried to make a run for there aunt, there maids however
had them hooked from behind by the collars of there cloths.

"Now, now Eric no need to go rushing off, be respectful and patient." One said,
as she gave the kid an especially hard yank. Sirce then followed Nove' to the 
corner of the room where they watched the group of children greet there aunt.
"Seems shes good with the kids." Nove' nodded. "Most of there parents are busy,
I mean Meldoa is too, she just somehow makes it all work." Sirce nodded, the 
scene clawing at is heart as his desire for his own grew.

Now, this witch had up ended his life, put all of his plans on hold, Sirce was 
never really intending to stay at the factory for every long, in fact he was
saving enough money to by a little corner, or at least space for a stall to sell
flowers from the family, well they might as well be in the gutter now. 
He exhaled, then feeling a strong pinch on his back. "Hmm." He muttered looking 
at Nove' in which he pointed to Meldoa whom was looking at him in a way that 
told him he should get his ass over there.

Sirce then put on his best face, nothing like a bright smile to melt all
suspicions away or gain some, you never know with people. He then stood next 
the witch, his wife, whom wrapped her arm around him, and he was forced to do 
the same, Sirce hid his displeasure and simply endured. "Children I'd like you 
to meet someone, this is Sirce, and he is my dear fiance." Two of the kids eyes
lit up especially the girls. He could not deny that her expression was cute.

"When are you going to get married." She said. Oh god, Sirce thought as he stared
at the little thing. "We'll see honey, that's all still a ways away." But there
was one child that possed a scowl one that had already asked why he existed here,
and this revelation seemed to have only deepened an already deep resentment of him,
Meldoa seemed to have taken notice too, for her expression changed for but a second,
but Sirce did not see that.

"Now children, I know that your excited and unruly from such a long drive but 
right now you should all head to your rooms and get established before supper."
Sirce nodded to himself. At least it would get this woman off of me, he thought.
The maids then rushed everyone along, the maids that belonged to the house 
guiding them to there assigned rooms. Meldoa then promptly detaching herself
from him. "You should hold me tighter, it will make it more believable."
Sirce fought his scowl. "Is there anything else you need me for." "No, also
make sure you talk to me as an equal." She then walked away, and headed back up 
the stairs, well I guess that just leaves me with the greenhouse not that I'm 
complaining. He thought as he immediately went back too where he was.
