== THE KINDLING OF HATE ENCAGED
:autofit-option:

Sirce stood behind Meldoa whom sat in a chair, looking at her father
who seemed to be taking everything well, but Sirce knew it was just a front and
that this was in fact his worse nightmare, Sirce felt a little camaraderie in that,
that he was not completely alone in his thoughts.

"Ha, so your my daughter's fiance, it's about time," he said with a giggle that betrayed
him, Sirce looked down at Meldoa, seeing poisonous smile stretched from ear to ear,
"indeed it is father indeed it is," I brought my hand out across my chest forming
it in a cup just like Nove' told him too, "my name is Sirce, Junias Ackscene,"
he nodded, "well then welcome to the family Sirce, I hope you treat my daughter well,"
Junias fought the words out of his mouth not that he necessarily hated Sirce, or
wouldn't accept him as a person but at the fact the most stable of his daughters
had actually done the unthinkable.

What the hell are you thinking, Junias wanted to shout but as with anything 
such a public outburst would not reflect kindly onto him, and now at this most
delicate moment in the relationship between the Ternia family, he needs the outward
appearance of the family to be strong. He looked up at Sirce, and decided perhaps he 
can make the unwilling participant crack under pressure. "So Meldoa, how did you 
meet this man, not a lot of humans like to come visit here," he was right the only
time apes actively came here was for an explicit purpose, like a diplomatic envoy,
or because they where forced to by other means, this would challenge the first
foundation of there 'love', how they met.

Meldoa smiled, "he was simply on an envoy trip, made a good first impression,
and we exchanged a few letters, and we eventually decided it was a good time to
do so." Junias leaned forward, it was not hard to tell that he was thinking deeply
Sirce was growing nervous as he thought about what it'd mean if he got confirmation,
that there relationship was a false one, what would she do.

Junias kept staring at the two, this is a waste of time I should just accost her
right here right now, he thought as he leaned back in his chair, "Sirce do you 
mind if you take a step out for right now," Sirce then looked at Meldoa, and she
and he went out the door.

"Meldoa, my daughter, what the hell are you doing," she leaned back and crossed
her legs, "oh whatever do you mean," she said sarcastically, "enough," her father
put on a tone she knew would only spell trouble if she didn't respond properly,
"I've force an ape to become my husband in order to stop you from pestering me."
They both sat in silence, the father exhaled, "in what way was I pestering you,"
she looked at her father disapprovingly, "oh, I don't know the blind dates, the 
weird meet ups with members of the opposite sex, the talks about artificial 
insemination," Junias pinched his brow, "Meldoa, I am looking out for you the 
family," Meldoa's face contorted, "oh really well how would you like if you where
told, by your father, to have sex with some random girl you just met," Junias
stared at the floor for a second. "Listen, I am... If your going to be come head
of this family, I want you to at least to have child... I need to make sure that
your legacy is preserved because the minute you enter my spot there will be 
people who will challenge your claim," she spoke slowly so that there would be 
no room more misinterpreted words, with him pausing every so often to collect his
thoughts, Meldoa remained firmed in her expression of anger.

"Really that's what this is about a linage, I understand my responsibility's,
but to be treated like this by my own father is disgusting," Junias felt a wound
produce itself one his soul, "Meldoa, I," Meldoa gripped the chair, "I hoped, 
you'd at least respect my agency and my ability to determine when the time was
right, and whom was deserving enough to receive that right," her father then 
looked off to the side of the room, feeling a coming onset of guilt,
"but clearly that's not the fucking case," Junias remained silent,
perhaps I have made an error, he thought to himself, perhaps I have been too 
hasty. 

"I'm sorry," Meldoa scoffed, "he will stay in my midst for the time
being," Junias picked up his head, "Meldoa" she then brought her hand onto her 
chin, "I have no reason to trust that you won't continue your assault, he will
stay, and if you continue your actions I will bear his child."

Junias understood all the implications of this, how this would send shock waves
though the wolfkin population, how the daughter of a wolfkin elite, produce a
mixed child, Junias shook at what could happen to the family if he kept her
in the fold and what it would mean losing her.

If she disguised as an elite it would seem like the marriage was completely
political, he could arrange a few shell companies to be made, do some fake
exports and imports that are favorable, as long as no child was born people
would scoff but they would understand, "your supposed to make my life easier
you know," she folded her arms, "you to," he closed his eyes, he knew he was in 
no position to decline this either this is her house and these are her rules.

"I'll support you in this endeavor, and I'll stop harassing you, just don't
conceive a child." She smiled, "thank you for coming to an understanding," he 
nodded exhaling, "anyways lets finally get back to talks about everyone else's
financial situations," Junias crossed his fingers hoping that the rest of his sons
and daughter have decided to be kind to him this year.
